<?php
// $Id$

include_once('crm_admin.features.inc');

/**
 * @file
 * Administrative views and panels for the CRM
 * @author Michael Prasuhn <mike@shomeya.com>
 * @link http://shomeya.com
 * @package crm_admin
 */

/* -----------------------------------------------------------------

  Hook Implementations

------------------------------------------------------------------ */

/**
 * Implementation of hook_block().
 */
function crm_admin_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['create_constituent_block'] = array(
      'info' => t('Create constituent block'),
      'cache' => BLOCK_CACHE_GLOBAL,
    );
    return $blocks;
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 'create_constituent_block':
        dialog_add_js();
        $links = array();
        $links[] = l(t('Add new consituent'), 'node/add/constituent');

        return array(
          'subject' => t('Title of block #1'),
          'content' => theme('item_list', $links),
        );
        break;

    }
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function crm_admin_nodeapi(&$node, $op, $a3, $a4) {
  $types = array('constituent', 'organization', 'notes', 'facilitator', 'participant');
  if ($op == 'load' && in_array($node->type, $types)) {
    global $custom_theme;
    $custom_theme = variable_get('admin_theme', '0');
    drupal_add_css(drupal_get_path('module', 'system') .'/admin.css', 'module');
  }
}

/**
 * Implementation of hook_init().
 */
function crm_init() {
  // Add admin CSS
  $router_item = menu_get_item();
  $admin_paths = array('admin/crm/reports');
  if (in_array($router_item['path'], $admin_paths)) {
    drupal_add_css(drupal_get_path('module', 'crm_admin') .'/crm_admin.css', 'theme');
  }
}

/**
 * Implementation of hook_form_alter().
 */
function crm_admin_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form['#parameters'][1]['view']->name == 'constituent_report_basic') {

  }
}
